In [13]:
#1
import numpy as np

# Define a 5x5 image matrix
image = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Define a 3x3 filter (kernel)
filter_kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

# Get the dimensions of the image and the filter
image_height, image_width = image.shape
filter_height, filter_width = filter_kernel.shape

# The output matrix dimensions (after convolution)
output_height = image_height - filter_height + 1
output_width = image_width - filter_width + 1
output = np.zeros((output_height, output_width))

# Perform convolution
for i in range(output_height):
    for j in range(output_width):
        # Extract the region of interest from the image (submatrix)
        region = image[i:i+filter_height, j:j+filter_width]
        
        # Perform element-wise multiplication and sum the result
        output[i, j] = np.sum(region * filter_kernel)

# Display the output of the convolution
print("Output after convolution:")
print(output)


Output after convolution:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#2
import numpy as np

# Define a 4x4 feature map
feature_map = np.array([
    [1, 3, 2, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Define the pool size (2x2)
pool_size = 2

# Calculate the dimensions of the output feature map
output_height = feature_map.shape[0] // pool_size
output_width = feature_map.shape[1] // pool_size
output = np.zeros((output_height, output_width))

# Perform max pooling
for i in range(output_height):
    for j in range(output_width):
        # Extract the region (2x2 window)
        region = feature_map[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size]
        
        # Take the maximum value in the region
        output[i, j] = np.max(region)

# Display the output of max pooling
print("Output after max pooling:")
print(output)


Output after max pooling:
[[ 6.  8.]
 [14. 16.]]


In [15]:
#3
import numpy as np

# Define a sample feature map (can be output from a convolutional layer)
feature_map = np.array([
    [1, -2, 3, -4],
    [-5, 6, -7, 8],
    [9, -10, 11, -12],
    [-13, 14, -15, 16]
])

# Apply the ReLU activation function
relu_output = np.maximum(0, feature_map)

# Display the output after ReLU
print("Output after ReLU activation:")
print(relu_output)


Output after ReLU activation:
[[ 1  0  3  0]
 [ 0  6  0  8]
 [ 9  0 11  0]
 [ 0 14  0 16]]


In [16]:
#4
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

# Step 1: Define random input data (e.g., 10 samples of 28x28 images with 1 channel)
# This could represent grayscale images of size 28x28.
input_data = np.random.random((10, 28, 28, 1))  # Shape: (batch_size, height, width, channels)

# Step 2: Define the CNN model
model = models.Sequential()

# Add a Convolutional Layer with 32 filters, a 3x3 kernel, and ReLU activation
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))

# Add a Flatten layer to reshape the output of the convolutional layer to a 1D vector
model.add(layers.Flatten())

# Add a Fully Connected (Dense) Layer with 10 units (assuming 10 classes for classification)
model.add(layers.Dense(10, activation='softmax'))  # softmax for multi-class classification

# Step 3: Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Define random target labels for training (10 samples, 10 classes)
# For the sake of demonstration, we create random labels (one-hot encoded)
target_labels = np.random.randint(0, 10, size=(10,))
target_labels = tf.keras.utils.to_categorical(target_labels, num_classes=10)

# Step 5: Train the model on the random data
model.fit(input_data, target_labels, epochs=5)

# Print the model summary to see the architecture
model.summary()


Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2000 - loss: 2.2539
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6000 - loss: 1.5978
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9000 - loss: 1.1779
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 1.0000 - loss: 0.8167
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.5297


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 21632)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │       216,330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 649,952 (2.48 MB)

 Trainable params: 216,650 (846.29 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 433,302 (1.65 MB)

In [ ]:
#5import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define a Simple CNN Model
model = tf.keras.Sequential([
    # Convolutional Layer with 32 filters and a 3x3 kernel
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(image_size, image_size, 1)),
    
    # Flatten the output of the convolutional layer
    tf.keras.layers.Flatten(),
    
    # Fully Connected Layer (Dense) with 10 units (for 10 classes)
    tf.keras.layers.Dense(10, activation='softmax')
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Display the Model Summary
model.summary()


Epoch 1/5
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.0903 - loss: 2.4878
Epoch 2/5


In [ ]:
!pip install tensorflow

In [ ]:
#6
import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the CNN Model
model = tf.keras.Sequential([
    # Convolutional Layer with 32 filters, a 3x3 kernel, and ReLU activation
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(image_size, image_size, 1)),
    
    # Max-Pooling Layer with a 2x2 window
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    # Flatten the output of the convolutional layer
    tf.keras.layers.Flatten(),
    
    # Fully Connected (Dense) Layer with 10 units (for 10 classes)
    tf.keras.layers.Dense(10, activation='softmax')
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Display the Model Summary
model.summary()


In [ ]:
#7
import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the CNN Model
model = tf.keras.Sequential([
    # Convolutional Layer with 32 filters, a 3x3 kernel, and ReLU activation
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(image_size, image_size, 1)),
    
    # Max-Pooling Layer with a 2x2 window
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    # Flatten the output of the convolutional layer (2D to 1D)
    tf.keras.layers.Flatten(),
    
    # Fully Connected Layer (Dense) with 128 units and ReLU activation
    tf.keras.layers.Dense(128, activation='relu'),
    
    # Output Layer with 10 units (for 10 classes) and Softmax activation
    tf.keras.layers.Dense(10, activation='softmax')
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Display the Model Summary
model.summary()


In [ ]:
#8
import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the CNN Model with Batch Normalization
model = tf.keras.Sequential([
    # Convolutional Layer with 32 filters, a 3x3 kernel, and ReLU activation
    tf.keras.layers.Conv2D(32, (3, 3), input_shape=(image_size, image_size, 1)),
    
    # Batch Normalization Layer
    tf.keras.layers.BatchNormalization(),
    
    # ReLU Activation Function
    tf.keras.layers.ReLU(),
    
    # Max-Pooling Layer with a 2x2 window
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    # Flatten the output of the convolutional layer (2D to 1D)
    tf.keras.layers.Flatten(),
    
    # Fully Connected Layer (Dense) with 128 units and ReLU activation
    tf.keras.layers.Dense(128, activation='relu'),
    
    # Output Layer with 10 units (for 10 classes) and Softmax activation
    tf.keras.layers.Dense(10, activation='softmax')
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Display the Model Summary
model.summary()


In [ ]:
#9
import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the CNN Model with Dropout Regularization
model = tf.keras.Sequential([
    # Convolutional Layer with 32 filters, a 3x3 kernel, and ReLU activation
    tf.keras.layers.Conv2D(32, (3, 3), input_shape=(image_size, image_size, 1)),
    
    # Dropout Layer with a dropout rate of 0.25
    tf.keras.layers.Dropout(0.25),
    
    # ReLU Activation Function
    tf.keras.layers.ReLU(),
    
    # Max-Pooling Layer with a 2x2 window
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    # Flatten the output of the convolutional layer (2D to 1D)
    tf.keras.layers.Flatten(),
    
    # Fully Connected Layer (Dense) with 128 units and ReLU activation
    tf.keras.layers.Dense(128, activation='relu'),
    
    # Dropout Layer with a dropout rate of 0.5 for regularization
    tf.keras.layers.Dropout(0.5),
    
    # Output Layer with 10 units (for 10 classes) and Softmax activation
    tf.keras.layers.Dense(10, activation='softmax')
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Display the Model Summary
model.summary()


In [ ]:
#10
import tensorflow as tf

# Load the pre-trained VGG16 model without the top (fully connected) layers
vgg16_model = tf.keras.applications.VGG16(weights='imagenet', include_top=True)

# Print the model summary (architecture)
vgg16_model.summary()


In [ ]:
#11
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the CNN Model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), input_shape=(image_size, image_size, 1)),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')  # Output layer with 10 classes
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model on the Synthetic Data and capture the history
history = model.fit(X_train, y_train, epochs=5, batch_size=32)

# Step 5: Plot the Accuracy and Loss Graphs
# Plotting accuracy
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.title('Training Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Plotting loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss', color='red')
plt.title('Training Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()


In [ ]:
#12
import tensorflow as tf

# Load the pre-trained ResNet50 model without the top (fully connected) layers
resnet50_model = tf.keras.applications.ResNet50(weights='imagenet', include_top=True)

# Print the model summary (architecture)
resnet50_model.summary()



In [ ]:
#13
import tensorflow as tf
import numpy as np

# Step 1: Generate Synthetic Data (Random Noise as Images)
num_samples = 1000  # Number of images in the dataset
image_size = 28  # Each image is 28x28 pixels
num_classes = 10  # Number of classes for classification

# Generate random images (e.g., 28x28 grayscale images)
X_train = np.random.random((num_samples, image_size, image_size, 1))  # Shape: (num_samples, 28, 28, 1)

# Generate random labels (one-hot encoded)
y_train = np.random.randint(0, num_classes, num_samples)
y_train = tf.keras.utils.to_categorical(y_train, num_classes)

# Step 2: Define the Basic CNN Model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), input_shape=(image_size, image_size, 1)),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax')  # Output layer with 10 classes
])

# Step 3: Compile the Model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 4: Train the Model and Print the Loss and Accuracy After Each Epoch
class PrintEpochEnd(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(f"Epoch {epoch+1}: Loss = {logs['loss']:.4f}, Accuracy = {logs['accuracy']:.4f}")

# Train the model and pass the custom callback to print loss and accuracy after each epoch
model.fit(X_train, y_train, epochs=5, batch_size=32, callbacks=[PrintEpochEnd()])
